services:
  mainsail:
    build:
      context: ./mainsail
      dockerfile: mainsail.Dockerfile
    ports:
      - 80:80
    networks:
      - mainsail
    restart: always

  moonraker:
    build:
      context: ./moonraker
      dockerfile: moonraker.Dockerfile
    ports:
      - 7125:7125
    networks:
      - mainsail
    volumes:
      - /opt/printer_data:/root/printer_data:z
    devices:
      - /dev/gpiochip0:/dev/gpiochip0
    security_opt:
      - label=level:s0
    user: 0:0
    restart: always

  klipper:
    build:
      context: ./klipper
      dockerfile: klipper.Dockerfile
    volumes:
      - /opt/printer_data:/root/printer_data:z
    devices:
      - ${MCU_1_DEVICE:-}:/dev/mcu1
      - ${MCU_2_DEVICE:-}:/dev/mcu2
      - ${MCU_3_DEVICE:-}:/dev/mcu3
      - ${MCU_4_DEVICE:-}:/dev/mcu4
    security_opt:
      - label=level:s0
    user: 0:0
    restart: always

  crowsnest:
    build:
      context: ./crowsnest
      dockerfile: crowsnest.Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 8083:8083
    volumes:
      - /opt/printer_data:/root/printer_data:z
      - /dev/v4l:/dev/v4l:ro
      - /dev/bus/usb:/dev/bus/usb:ro
    networks:
      - mainsail
    devices:
      - ${CAMERA_1_DEVICE}:/dev/video0
      - ${CAMERA_2_DEVICE}:/dev/video1
      - ${CAMERA_3_DEVICE}:/dev/video2
      - ${CAMERA_4_DEVICE}:/dev/video3
    security_opt:
      - label=disable
    privileged: true
    user: 0:0
    restart: always

networks:
  mainsail:
